//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrPract4._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectId
    {
        public int ID_ConnectId { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> Clients_ID { get; set; }
        public Nullable<int> Coffee_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Coffee Coffee { get; set; }
        public virtual EMP EMP { get; set; }
    }
}
